# Site settings
email: studio@xxix.co
description: > # this means to ignore newlines until "baseurl:"
  This is the documentation for updating [theampalcreative.com](http://www.theampalcreative.com).
baseurl: "/xxix-docs" # the subpath of your site, e.g. /blog/
client: "Ampal"

# Build settings
markdown: kramdown
